name: NTC
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.5
  gap: ^3.0.1
  shared_preferences: ^2.2.2
  lottie: ^3.0.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  awesome_dialog: ^3.2.1
  email_validator: ^3.0.0
  flutter_blue_classic: ^0.0.4
  get: ^4.6.5
  permission_handler: ^12.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  open_filex: ^4.5.0
  pdf: ^3.11.1
  printing: ^5.12.1
  showcaseview: ^4.0.1
  workmanager: ^0.6.0
  uuid: ^4.5.0




  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_utils: ^2.8.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
 
