name: smart_medic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.6.5
  gap: ^3.0.1
  shared_preferences: ^2.2.2
  lottie: ^3.0.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  awesome_dialog: ^3.2.1
  email_validator:







  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
 
